
apiversion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cammie-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer"
spec:
  tls:
  - hosts:
    - cammie-nodejs.cit270.com
    secretName: -cammie-dev-tls
  rules:
  - host: cammie-loadbalancer.cit270.com
    http:
      paths:
      - backend:
        serviceName: cammie-cit270-loadbalancer
        servicePort: 80